### ISSUE TITLE
add unique id to the code block

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz.io-old#1001]
right now there is no way to assign the unique id to the code block copy button

<img width="885" alt="Screenshot 2023-07-21 at 10 46 05 AM" src="https://github.com/SigNoz/signoz.io/assets/88981777/23d9aff0-1662-442e-8c9c-6da35397cbb2">

**Comment by Calm-Rock** [comment]
@palashgdev has this been done ?

**Comment by palashgdev** [comment]
no not required as of now
