### ISSUE TITLE
Update link for OpenTelemetry python instrumentation library in docs

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io-old#110]
## Bug description

*Please describe.* 
Link for OpenTelemetry python instrumentation library is not working on this page: https://signoz.io/docs/instrumentation/python

![Screenshot 2021-05-29 at 2 59 22 PM](https://user-images.githubusercontent.com/83692067/120065343-7a057880-c08e-11eb-850f-bcf48ddb5ae4.png)
![Screenshot 2021-05-29 at 3 00 13 PM](https://user-images.githubusercontent.com/83692067/120065372-95708380-c08e-11eb-9e65-1e5d65dc4f50.png)

**Comment by pranay01** [comment]
@ankit01-oss It seems this is still not fixed? What pages are users using in user testing?

**Comment by pranay01** [comment]
This is fixed now
