### ISSUE TITLE
Add docs on Apdex

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io-old#1102]
This is linked in our product: https://signoz.io/docs/userguide/metrics/#apdex?utm_source=product&utm_medium=frontend&utm_campaign=apdex

But this page does not have any info in Apdex.

**Comment by Calm-Rock** [comment]
This has been updated in the mentioned link.

**Comment by Calm-Rock** [comment]
This has been updated in the mentioned link.
