### ISSUE TITLE
Add instructions on how to monitor JVM metrics in SigNoz

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#112]
SigNoz does support JVM metrics as part of Metrics dashboard but this is not explicitly explained in the docs. We should add it in the UserGuid section of the docs as well

Instructions on how to enable this can be found here - https://signoz.notion.site/Adding-JVM-metrics-from-Springboot-40c3b026573f435b932f3a42f8983e13

**Comment by Harshal0902** [comment]
@pranay01 can you please assign this issue to. I would like to work on this issue.
