### ISSUE TITLE
Add scroll to top text at the footer

### ISSUE THREAD

**Issue by Harshal0902** [SigNoz/signoz.io-old#114]
## Is your feature request related to a problem?

If I need to access the navbar I need to scroll to the top, any its sometimes very frustrating to scroll again and again to the top of the page which very long(such as the [blog page](https://signoz.io/blog/).

## Describe the solution you'd like
Add a scroll to top text at the footer of the page so that it is convenient for the user to easily scroll to the top instead of scrolling again and again every time.

## Describe alternatives you've considered
Making the navbar fixed and making the blurred navbar once user scroll down to the page.

## Additional context
Here is a Figma prototype where the scroll top text is present below the Subscribe section.
![image](https://user-images.githubusercontent.com/64153988/146045016-70baa063-d10d-48c6-89ee-fe6ac523d202.png)

#### *Thank you* for your feature request – we love each and every one!

**Comment by makeavish** [comment]
@pal-sig On https://docusaurus.io/ when you scroll up the navbar reappears, is it config change?

<img width="2290" alt="Screenshot 2021-12-22 at 15 46 45" src="https://user-images.githubusercontent.com/9512100/147076814-b3775ef6-708b-4d99-9d99-936616845174.png">

**Comment by palashgdev** [comment]
> @pal-sig On https://docusaurus.io/ when you scroll up the navbar reappears, is it config change?
> 
> <img alt="Screenshot 2021-12-22 at 15 46 45" width="2000" src="https://user-images.githubusercontent.com/9512100/147076814-b3775ef6-708b-4d99-9d99-936616845174.png">

No @makeavish there is extra style which is stopping this behaviour

**Comment by palashgdev** [comment]
> > @pal-sig On https://docusaurus.io/ when you scroll up the navbar reappears, is it config change?
> > <img alt="Screenshot 2021-12-22 at 15 46 45" width="2000" src="https://user-images.githubusercontent.com/9512100/147076814-b3775ef6-708b-4d99-9d99-936616845174.png">
> 
> No @makeavish there is extra style which is stopping this behaviour

could be a another good first issue i guess

**Comment by pranay01** [comment]
I think this may not be very relevant issue, also the scroll to top button may coincide with chat button. Closing for now
