### ISSUE TITLE
Navbar: search bar and "Try signoz cloud" button overlap eachother in tab device mode

### ISSUE THREAD

**Issue by RajeevDash007** [SigNoz/signoz.io-old#1151]
![Firefox_Screenshot_2023-09-23T13-02-39 265Z](https://github.com/SigNoz/signoz.io/assets/96860040/d9af599b-be2c-44e9-be92-065d53fa124f)

**Comment by Calm-Rock** [comment]
We have migrated to a new website and this seems to work fine now. 

Closing this issue - please raise a new one at https://github.com/SigNoz/signoz-web if you still feel this still doesn't work for you.
