### ISSUE TITLE
Allow edit doc option for users

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz.io-old#119]
Clickhouse allows users to edit official documentation by just clicking the edit button and then create a PR.
Eg: https://clickhouse.com/docs/en/

<img width="1873" alt="Screenshot 2021-12-22 at 15 48 32" src="https://user-images.githubusercontent.com/9512100/147077043-bac55342-c3be-4642-8067-83362fc3f1df.png">

This would promote user doc contribution and improve our docs.

**Comment by makeavish** [comment]
Clickhouse documentation management: https://github.com/ClickHouse/ClickHouse/blob/master/docs/tools/README.md

**Comment by makeavish** [comment]
Even Posthog has edit button and issue button too: https://posthog.com/docs

**Comment by pranay01** [comment]
@makeavish Will check this - it seems docusaurus also has this feature, need to figure out how to enable this - https://docusaurus.io/docs/2.0.0-beta.13#something-missing

**Comment by pranay01** [comment]
https://github.com/SigNoz/signoz.io/commit/bac800f45b7dd0d396faad4d4e7aa6cb831ae6ca this solves this issue
