### ISSUE TITLE
Create docs on - how to send cloudwatch logs on SigNoz

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io-old#1212]
Update the website docs with docs for "How to send Cloudwatch logs on SigNoz"

**Comment by pranay01** [comment]
Public link for the docs instruction - https://signoz.notion.site/AWS-Cloudwatch-logs-signoz-e93d6c3d220c485682f527663f0abfda

**Comment by Calm-Rock** [comment]
The docs are live [here](https://signoz.io/docs/userguide/send-cloudwatch-logs-to-signoz/)
