### ISSUE TITLE
Add the variables that can be used in the Alert template namespace

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io-old#1224]
There is no list of the variables that can be used in the Alert template namespace.

For example -> `{{.Labels.serviceName}}`, `{{.Annotations.}}` etc

This list needs to be listed in [this section](https://signoz.io/docs/userguide/alerts-management/) of the docs

**Comment by msiepracki** [comment]
is there any progress on this?

**Comment by al-mcintosh** [comment]
Subscribed for updates.  I can send a general alert that says container restarted, but we don't know which container restarted until someone investigates.
