### ISSUE TITLE
Update hostmetrics section on otel binary installation docs

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io-old#1236]
Need to update this section on https://signoz.io/docs/tutorial/opentelemetry-binary-usage-in-virtual-machine/

<img width="1147" alt="Screenshot 2023-10-26 at 8 47 49 AM" src="https://github.com/SigNoz/signoz.io/assets/83692067/688cf6e2-4e13-42a5-bc52-3bcc82171874">

**Comment by Calm-Rock** [comment]
@ankit01-oss , I have raised a [PR](https://github.com/SigNoz/signoz.io/pull/1235). Please review.
