### ISSUE TITLE
Improve docs of Trace Details page and Metrics page 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#128]
With help icon feature shipped in v0.5.4, more people will see Trace Details page docs. As of now it doesn't have any details and is just a barebone screenshots page.

https://signoz.io/docs/userguide/trace-details/

**Comment by Calm-Rock** [comment]
The trace-details page link provided above is not available now. 

I will be doing a thorough review of the whole documentation when I will take up the sanity check for documentation.

Closing this issue.
