### ISSUE TITLE
Support search on the blog and docs on the website

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz.io-old#136]
How to add search: https://docusaurus.io/docs/search

**Comment by nishit-g** [comment]
Hey I would love to give this a try @makeavish , are we going with Algolia or local search ?

**Comment by makeavish** [comment]
@pal-sig Can you please assit @nishit-g for this issue?

**Comment by palashgdev** [comment]
Hi @nishit-g 

There is a details docs for same in [the link](https://docusaurus.io/docs/search#using-algolia-docsearch)

**Comment by pranay01** [comment]
@nishit-g I think we should enable search only in docs for now.

**Comment by palashgdev** [comment]
@nishit-g You can start from [here](https://github.com/algolia/docsearch/)

**Comment by nishit-g** [comment]
Hey @pal-sig should I go ahead and apply [here](https://docsearch.algolia.com/apply/) to get appId and apiKey ? 

```js
themeConfig: {
    // ...
    algolia: {
      // If Algolia did not provide you any appId, use 'BH4D9OD16A'
      appId: 'YOUR_APP_ID',

      // Public API key: it is safe to commit it
      apiKey: 'YOUR_SEARCH_API_KEY',

      indexName: 'YOUR_INDEX_NAME',

      // Optional: see doc section below
      contextualSearch: true,

      // Optional: Specify domains where the navigation should occur through window.location instead on history.push. Useful when our Algolia config crawls multiple documentation sites and we want to navigate with window.location.href to them.
      externalUrlRegex: 'external\\.com|domain\\.com',

      // Optional: Algolia search parameters
      searchParameters: {},

      //... other Algolia params
    },
  }
```

**Comment by pranay01** [comment]
@nishit-g I have applied for the app id

Though I am not sure if this should available publicly in open source. Need to check that

I will get back to you on this

![Screenshot 2021-12-29 at 11 26 56 PM](https://user-images.githubusercontent.com/504541/147690400-7b0af8a6-9151-4a74-8208-f1f949073637.png)

**Comment by nishit-g** [comment]
Sure! @pranay01

**Comment by pranay01** [comment]
@nishit-g I have got algolia API key now - do you want to pick up this issue? Please DM me on our slack community so that I can share the API keys with you there - https://signoz.io/slack

**Comment by nishit-g** [comment]
DM'd @pranay01

**Comment by pranay01** [comment]
@nishit-g this was a simple couple of lines fix, so added it myself. thanks for doing the initial research and pointing us in the right direction

Search is available in docs now
