### ISSUE TITLE
Docs needed for collecting logs from EC2 instances to SigNoz (self-host and cloud)

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io-old#1392]

**Comment by Calm-Rock** [comment]
Done for SigNoz Cloud: https://signoz.io/docs/aws-monitoring/ec2-logs/

**Comment by Calm-Rock** [comment]
Creating a separate issue for self-hosted - https://github.com/SigNoz/signoz-web/issues/90
