### ISSUE TITLE
Remove hostmetrics and prometheus receiver from installation of otel collector

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io-old#1401]
Remove hostmetrics and prometheus receiver from installation of otel collector from places it is not required in onboarding docs. For example, application logs.

**Comment by ankit01-oss** [comment]
Please verify this with @Calm-Rock whether this is true

**Comment by Calm-Rock** [comment]
Addressed in PR #4295 of onboarding.
