### ISSUE TITLE
For infrastructure monitoring, have separate flows for hostmetrics and prometheus in onboarding docs

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io-old#1402]
Currently for hostmetrics in infrastructure monitoring, we have both hostmetrics and prometheus receiver added in the config file. We need to let users know when should a particular receiver be used.

**Comment by ankit01-oss** [comment]
The issue is in onboarding docs for hostmetrics we have two receivers enables: hostmetrics and prometheus. Why are two receivers needed? Clarify and update accordingly.

**Comment by Calm-Rock** [comment]
We will need the hostmetrics receiver for collecting the hostmetrics. For prometheus, the receiver isn't active because the target for it is commented out - which you can see as `# - localhost:8888`. Until this target is not defined, the receiver won't 
won't work.
