### ISSUE TITLE
Upgrade docusaurus to 2.0.0-beta.18

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#189]

**Comment by pranay01** [comment]
Getting this error in doing yarn build after changing to beta15 in `package.json`
![Screenshot 2022-02-17 at 10 42 49 PM](https://user-images.githubusercontent.com/504541/154534487-d450aada-777f-4d53-b5f3-871b5f86f0d9.png)

**Comment by pranay01** [comment]
Facing same issue in beta 16

![Screenshot 2022-03-03 at 12 46 04 PM](https://user-images.githubusercontent.com/504541/156515482-31313af8-b2f0-4e37-829b-81aee05db266.png)

**Comment by pranshuchittora** [comment]
Spent significant time and found out there there were some breaking changes in terms of how we import things. https://github.com/facebook/docusaurus/discussions/6516#discussioncomment-2078793

Tried resolving some of them but not able to resolve them all.

<img width="883" alt="Screenshot 2022-04-12 at 16 53 18" src="https://user-images.githubusercontent.com/32242596/162949623-8d5dda5b-6f99-4fdd-a890-187b9b323d68.png">

**Comment by pranay01** [comment]
This was fixed
