### ISSUE TITLE
Update Django section of Python instrumentation Docs

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz.io-old#208]
Update https://signoz.io/docs/instrumentation/python/#instrumenting-django-applications to link https://signoz.io/blog/opentelemetry-django/

**Comment by makeavish** [comment]
@ankit01-oss We have to make sure to update docs section as soon as we publish blog for sample app instrumentation.

**Comment by pranay01** [comment]
@makeavish @ankit01-oss Whats the status of this issue? On whom is it pending on

**Comment by makeavish** [comment]
@pranay01 It's pending on @ankit01-oss.

**Comment by ankit01-oss** [comment]
made the PR: https://github.com/SigNoz/signoz.io/pull/269
