### ISSUE TITLE
Add Typescript Swizzled components

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz.io-old#244]

**Comment by pranay01** [comment]
@palash-signoz Can you share more details on this issue? Not clear what is the issue

**Comment by Calm-Rock** [comment]
@palashgdev can you provide more context on this? Are we talking about using [swizzling](https://docusaurus.io/docs/swizzling) for more customization?

**Comment by pranay01** [comment]
Yeah, that was the intent. I think we can close this for now and open a new issue if needed
