### ISSUE TITLE
The collapse  section is behaving erratically

### ISSUE THREAD

**Issue by sf-pchakraborty** [SigNoz/signoz.io-old#266]
Steps to replicate - 

Scroll down to the 'Frequently Asked Questions' section - 

Click on one of the expand buttons 
Click again to collapse, it doesn't work.

PFA screenshot - 
![Screenshot 2022-04-17 at 21 03 37](https://user-images.githubusercontent.com/30225487/163725429-6b03b17e-859c-479e-b427-11a395a8ad0e.png)

**Comment by pranay01** [comment]
@sf-pchakraborty Thanks for sharing the issue. Can you also share a short video of the issue you are facing? Would help us understand the problem better

**Comment by palashgdev** [comment]
debug: Some how antd css is not loading here

**Comment by palashgdev** [comment]
@pranay01 repo is not importing `@import '~antd/dist/antd.css';` seems each and every component is breaking here
