### ISSUE TITLE
Incorrect user message when empty email is provided on Signup to receive updates

### ISSUE THREAD

**Issue by pranshuchittora** [SigNoz/signoz.io-old#268]
https://user-images.githubusercontent.com/32242596/164169703-1d9853c8-6b57-4ca2-8303-f0e4aeed42ba.mov

**Comment by pranshuchittora** [comment]
@ankit01-oss is this the expected behaviour 🤔

**Comment by pranay01** [comment]
@pranshuchittora This is a bug, thanks for pointing. will fix

**Comment by pranay01** [comment]
this is fixed now
