### ISSUE TITLE
Shift SigNoz.io to NextJS + Docusaurus

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#292]
https://github.com/SigNoz/engineering-pod/issues/329

**Comment by pranshuchittora** [comment]
Rough Task List

- [ ] Project setup - 2 Days
- [ ] Create base components
    - [ ] Nav Bar
    - [ ] Footer
    - [ ] Carousal
    - [ ] Post Card

**Comment by palashgdev** [comment]
@pranay01 do need dark mode also in this because i am only able to see light mode design

**Comment by pranay01** [comment]
No, in the new website. We will not have light mode in the new website

**Comment by palashgdev** [comment]
do we have scope of dark mode in future ?

**Comment by pranay01** [comment]
If its easy to support, we can keep a flag for this

**Comment by palashgdev** [comment]
nothing is easy ... we need to design application accordingly

**Comment by pranay01** [comment]
Ok, then lets not do dark mode

**Comment by palashgdev** [comment]
Task:

- [ ] https://github.com/SigNoz/engineering-pod/issues/584
- [ ] https://github.com/SigNoz/engineering-pod/issues/585
