### ISSUE TITLE
Update Ruby on Rails docs section

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz.io-old#296]
We have recently published [blog](https://signoz.io/blog/opentelemetry-ruby/) on how to instrument Ruby on Rails app using opentelementry.
Using that as source we have to update our Ruby on Rails [docs](https://signoz.io/docs/instrumentation/ruby-on-rails/).

**Comment by ankit01-oss** [comment]
@pranay01 can you take this up plz?

**Comment by pranay01** [comment]
ok. I have already added a link to the blog for the time being

**Comment by ankit01-oss** [comment]
ok

**Comment by pranay01** [comment]
docs are updated. I have added the link to blog at the end as well
