### ISSUE TITLE
Add docs on how to monitor metrics for hosts in which SigNoz is not running

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#309]

**Comment by prashant-shahi** [comment]
@pranay01 can you assign this to me?

**Comment by pranay01** [comment]
@prashant-shahi done

**Comment by Calm-Rock** [comment]
@prashant-shahi was this done ?

**Comment by prashant-shahi** [comment]
@Calm-Rock yes, the following `otel-binary` docs was the addition.

https://signoz.io/docs/tutorial/opentelemetry-binary-usage-in-virtual-machine/
