### ISSUE TITLE
Add details on docs on what type of services will come in External Calls tab in metrics page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#341]
- [ ] Will DynamoDB calls appear as external calls?
- [ ] Will S3 calls appear as external calls?
- [ ] Will call to another service appear as external call?

What is the mechanism by which SigNoz identifies what will appear in External calls?

![Screenshot 2022-06-02 at 8 13 26 PM](https://user-images.githubusercontent.com/504541/171655737-fea35a2f-b0ea-45e4-8101-910c1e6db9c0.png)

**Comment by pranay01** [comment]
@ankitnayan Can you share more details on this so that this can be updated in the docs?

**Comment by pranay01** [comment]
the current logic external calls tab is `span kind=client` and the span must have `http.url` as attribute. Here is the code https://github.com/SigNoz/opentelemetry-collector-contrib/blob/develop/processor/signozspanmetricsprocessor/processor.go#L512-L518

If any client call does not contain `http.url` it won’t be showed in UI

For DB calls, `span.kind=3` and `db.system` should be present as span attribute which can be seen from code https://github.com/SigNoz/opentelemetry-collector-contrib/blob/develop/processor/signozspanmetricsprocessor/processor.go#L520-L525

**Comment by ankitnayan** [comment]
Fixed by https://github.com/SigNoz/opentelemetry-collector-contrib/pull/1307

**Comment by pranay01** [comment]
@srikanthccv can you make updates in docs based on the referrenced PR. 
This is the relevant section which needs to be udpated - https://signoz.io/docs/userguide/metrics/#external-calls
