### ISSUE TITLE
docs : Segregate docs for different alert channels in separate pages for better accessibility

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#361]
Currently SigNoz supports following alert channels, but docs are not clear on how to use them 

- [ ] Webhook
- [ ] Slack
- [ ] Pagerduty

**Comment by pranay01** [comment]
related https://github.com/SigNoz/signoz/issues/1248

**Comment by pranay01** [comment]
The docs for each channel is available now, though it could be segregated in different pages for easier accessibility @Calm-Rock

**Comment by Calm-Rock** [comment]
This is something even I felt we should have while doing the sidebar restructure. Have created a new issue for this Pranay #1365

**Comment by pranay01** [comment]
sounds good
