### ISSUE TITLE
Update steps for enabling receivers in Docs

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io-old#434]

**Comment by ankit01-oss** [comment]
@pranay01 will update after completing the article on Redis monitoring.

**Comment by pranay01** [comment]
sure

**Comment by Calm-Rock** [comment]
@ankit01-oss is this done ? 
We have [these docs](https://signoz.io/docs/userguide/send-metrics/) for enabling metrics receivers.

If not then please provide more details about what needs to be updated.
If done then please close this issue.

**Comment by ankit01-oss** [comment]
@Calm-Rock yes we can close this
