### ISSUE TITLE
remove outdated blogs which show SigNoz using Prometheus and other deprecated tech

### ISSUE THREAD

**Issue by zriyansh** [SigNoz/signoz.io-old#446]
example - https://github.com/SigNoz/signoz.io/blob/main/blog/2019-11-29-out-of-box-application-monitoring-prometheus.md.

and more

**Comment by Calm-Rock** [comment]
@zriyansh was this issue resolved ?

cc: @ankit01-oss

**Comment by zriyansh** [comment]
@Calm-Rock nope, the blog is still there which does not reflect signoz's current architecture at all

**Comment by ankit01-oss** [comment]
Adding a deprecated callout to the top of the blog. Will need to look into how to remove a blog without affecting SEO.
