### ISSUE TITLE
Add docs for missing spans scenario in trace details page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#477]
Currently, trace detail page does show missing spans in some cases but it doesn't have related docs. The link for this is pointed in the product, but it is not added yet in docs.

The docs related to missing spans should be added here
https://signoz.io/docs/userguide/traces/#missing-spans

**Comment by Calm-Rock** [comment]
@pranay01 do we still face this issue of missing spans in trace details page ?
I don't think we have anything live at this link https://signoz.io/docs/userguide/traces/#missing-spans

**Comment by pranay01** [comment]
yes, we have added this link in product https://signoz.io/docs/userguide/traces/#missing-spans but we don't have relevant docs ( though the section link is created) 

You should sync with Vishal and update this.
