### ISSUE TITLE
Add more office hrs videos as carousel in landing page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#525]
adding carousels in [signoz.io](http://signoz.io/) landing page  to show more videos as a carousel 

Loom Video with issue description: https://www.loom.com/share/b82c8bc00151423e920efbd2a37244e9

Video to be added:
https://www.youtube.com/watch?v=MLraw3pjYy8

**Comment by Calm-Rock** [comment]
@pranay01 is this still relevant ?

**Comment by pranay01** [comment]
not relevant. our website design has changed. closing
