### ISSUE TITLE
Github starts aren't showing up in the navbar

### ISSUE THREAD

**Issue by sf-pchakraborty** [SigNoz/signoz.io-old#582]
Now that we have crossed 10k starts , the number isn't showing up in the navbar

![Screenshot 2022-10-19 at 7 13 44 AM](https://user-images.githubusercontent.com/30225487/196590290-f6bb024c-6065-48fc-99e3-014d3304072a.png)

**Comment by Calm-Rock** [comment]
Closing this issue as it is resloved.
