### ISSUE TITLE
Check email format on webhook

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz.io-old#584]
If the email format is incorrect, then backend integrations to webhook fail to work on the email and the request gets added to the queue of webhook provider to retry later. When the webhook queue gets filled, further calls to webhook respond with the error `Queue is full`.
 Requesting email format validation at https://github.com/SigNoz/signoz.io/blob/main/src/theme/Footer/index.js#L50 so that backend does not reject the email and the webhook queue does not get full.

**Comment by palashgdev** [comment]
Input from the user is checking the length should be greater than 4 we need to check for type email

**Comment by palashgdev** [comment]
@ankitnayan getting unauthorised for this curl 

```bash
curl 'https://api.telegram.org/bot1641579317:AAGHqzQKOT9R3Wcxx7ZgHZcI0Vi6CzjmncY/sendMessage?chat_id=521831111&text=Email%20subscription%20-%20palash@signoz.io' \
  -H 'authority: api.telegram.org' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en;q=0.5' \
  -H 'origin: https://deploy-preview-589--frosty-austin-928e43.netlify.app' \
  -H 'referer: https://deploy-preview-589--frosty-austin-928e43.netlify.app/' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
  --compressed
```

**Comment by ankitnayan** [comment]
> @ankitnayan getting unauthorised for this curl
> 
> ```shell
> curl 'https://api.telegram.org/bot1641579317:AAGHqzQKOT9R3Wcxx7ZgHZcI0Vi6CzjmncY/sendMessage?chat_id=521831111&text=Email%20subscription%20-%20palash@signoz.io' \
>   -H 'authority: api.telegram.org' \
>   -H 'accept: */*' \
>   -H 'accept-language: en-GB,en;q=0.5' \
>   -H 'origin: https://deploy-preview-589--frosty-austin-928e43.netlify.app' \
>   -H 'referer: https://deploy-preview-589--frosty-austin-928e43.netlify.app/' \
>   -H 'sec-fetch-dest: empty' \
>   -H 'sec-fetch-mode: cors' \
>   -H 'sec-fetch-site: cross-site' \
>   -H 'sec-gpc: 1' \
>   -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
>   --compressed
> ```

we should no longer work with telegram APIs. What is it used for?

**Comment by palashgdev** [comment]
in the footer, it is used in the current signoz.io

**Comment by ankitnayan** [comment]
for subscribing?

@pranay01 we should remove telegram APIs now. Where to send the new data?

**Comment by ankitnayan** [comment]
@palashgdev isn't sending subscribing data to telegram independent of this issue? I mentioned the data going to integromat. Is the data going to both integromat and telegram?

**Comment by palashgdev** [comment]
>@palashgdev isn't sending subscribing data to telegram independent of this issue? I mentioned the data going to integromat. Is the data going to both integromat and telegram?

yeah this can be addressed in new issue

**Comment by pranay01** [comment]
> @pranay01 we should remove telegram APIs now. Where to send the new data?

I think we should senf to hubspot. As we do in the new website.
@palashgdev you are aware on how to do this right?
