### ISSUE TITLE
Add docs on how to get infrastructure metrics using hostmetrics receivers and dashboards

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#652]
These may be good places to start
1. Send metrics - https://signoz.io/docs/userguide/send-metrics/
2. Use hostmetrics json chart to create dashboards - https://github.com/SigNoz/dashboards/tree/main/hostmetrics

**Comment by Calm-Rock** [comment]
Closing this as we have these docs: https://signoz.io/docs/userguide/hostmetrics/
