### ISSUE TITLE
Incorrect config in tutorial of running otel-collector as binary

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz.io-old#822]
On following https://signoz.io/docs/tutorial/opentelemetry-binary-usage-in-virtual-machine/#plain-binary-1

```
collector server run finished with error: invalid configuration: service references extension "pprof" which does not exist
```

**Comment by srikanthccv** [comment]
Also https://github.com/SigNoz/benchmark/blob/main/docker/standalone/config.yaml#L50

<img width="649" alt="image (1)" src="https://user-images.githubusercontent.com/22846633/223095169-0066970c-a916-4af7-8b97-35ad02126bc6.png">
