### ISSUE TITLE
Add docs for agent based telemetry collection

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz.io-old#826]
The docs today to instrument an application with OpenTelemetry mostly send data to SigNoz directly.  
This issue requests to add docs to send data to SigNoz via otel-agent as the production setup of SigNoz recommends running SigNoz in an independent cluster and the cluster having applications should send data to SigNoz via otel-agent running on each VM

**Comment by Calm-Rock** [comment]
We have docs available for this now - specifically talking in the context of SigNoz Cloud.

Closing this. Please re-open if you find that this is still relevant.
