### ISSUE TITLE
Unknown processors type logstransform

### ISSUE THREAD

**Issue by sudhanshud** [SigNoz/signoz.io-old#839]
I am facing the "Unknown processors type logstransform" when using this processor to apply custom operator. Below are the otel collector agent logs.
`* error decoding 'processors': unknown type: "logstransform" for id: "logstransform/keepattrs" (valid values: [k8sattributes resource routing cumulativetodelta deltatorate groupbyattrs spanmetrics tail_sampling redaction resourcedetection servicegraph filter groupbytrace batch memory_limiter datadog probabilistic_sampler span transform attributes experimental_metricsgeneration metricstransform])
2023/03/20 05:37:12 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:`

**Comment by sudhanshud** [comment]
Above issue solved by using signoz distribution of otel collector. Below are the changes made in values.yaml([https://github.com/SigNoz/charts/blob/625b48373cc8d20c08376047c473035eba2b9b26/charts/k8s-infra/values.yaml](https://github.com/SigNoz/charts/blob/625b48373cc8d20c08376047c473035eba2b9b26/charts/k8s-infra/values.yaml)).

`otelAgent:
  name: "otel-agent"
  image:
    registry: docker.io
    repository: signoz/signoz-otel-collector
    tag: 0.66.6
    pullPolicy: IfNotPresent
 
  command:
    # -- OtelAgent command name
    name: /signoz-collector
    # -- OtelAgent command extra arguments
    extraArgs: []`

Screenshot for ur ref.
![Screenshot 2023-03-20 at 2 58 19 PM](https://user-images.githubusercontent.com/10415978/226298942-7508abc0-b449-49f1-b6f7-030754bc00b0.png)

**Comment by Calm-Rock** [comment]
Thanks for providing a solution for the issue @sudhanshud. Closing this as it is resolved.
