### ISSUE TITLE
How is SigNoz different from Grafana?

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz.io-old#846]
A blog on how is SigNoz different than below would be very helpful to the users

- [ ] Grafana Cloud
- [ ] Grafana's stack of Loki, Tempo, Mimir, Grafana
- [ ] Using clickhouse datasource in Grafana

**Comment by Calm-Rock** [comment]
@ankit01-oss - blog ideas for your reference. Adding a Blog tag to this.

PS: Please close this if it is not relevant.

**Comment by ankit01-oss** [comment]
We have created a page for this: https://signoz.io/comparisons/signoz-vs-grafana/
