### ISSUE TITLE
[DOCS]collecting_application_logs_otel_sdk_python outdated

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz.io-old#931]
https://signoz.io/docs/userguide/collecting_application_logs_otel_sdk_python/ is outdated

**Comment by ankit01-oss** [comment]
@nityanandagohain okay, should we pull it down for now or you will be sending a PR soon?

**Comment by nityanandagohain** [comment]
We can remove the contents and can we ask them to look here https://github.com/open-telemetry/opentelemetry-python/tree/main/docs/examples/logs

I will updated the doc once I have some bandwith with a proper example

**Comment by ankit01-oss** [comment]
Okay, can you review this once: https://github.com/SigNoz/signoz.io/pull/933

We should have an example including SigNoz once you have the bandwidth.

**Comment by nityanandagohain** [comment]
have approved the request, thanks 👍
