### ISSUE TITLE
Add docs for OTLP exporter with TLS

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz.io-old#951]
- Without TLS
- With TLS but self signed certificates
- With TLS

**Comment by Calm-Rock** [comment]
@srikanthccv has this been done ?

If not, can you please give more context about this?

**Comment by srikanthccv** [comment]
We don't need to do this now unless users ask us.

**Comment by Calm-Rock** [comment]
Cool. Will close this issue for now then. If a user asks for this, we can create a new issue for it.
