### ISSUE TITLE
Test golang sample instrumentation docs

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz.io-old#97]

**Comment by makeavish** [comment]
App is working fine.
Suggestions:

- Port number missing on blog post: https://signoz.io/opentelemetry/go/ @ankit01-oss 
- Remove the step for testing sample app @ankit01-oss 
- Create new sample app with UI (current app has only APIs) @makeavish 
- First section about installing SigNoz doesn't seem to be intuitive @ankit01-oss

**Comment by Calm-Rock** [comment]
@makeavish is this issue still relevant? 
If yes, can you mention which things need to be improved here and provide additional information regarding that?

**Comment by ankit01-oss** [comment]
I think we can close this @Calm-Rock as we have recently tested golang instrumentation docs.

**Comment by Calm-Rock** [comment]
Closing this as the docs were recently tested.
