### ISSUE TITLE
Elixir instrumentation as mentioned in the blog does not work 

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz.io-old#974]
Outdated Repo: https://github.com/SigNoz/elixir_otel_sample. Got below error when running `mix ecto.setup`.

```
** (MatchError) no match of right hand side value: {:error, :eaccess}
    (mix 1.13.4) lib/mix/compilers/application_tracer.ex:220: Mix.Compilers.ApplicationTracer.write_manifest/1
    (mix 1.13.4) lib/mix/compilers/application_tracer.ex:161: Mix.Compilers.ApplicationTracer.stop/1
    (mix 1.13.4) lib/mix/compilers/elixir.ex:179: Mix.Compilers.Elixir.compile/7
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
```

Sync the outdated repo with the official contrib repo example which works fine. https://github.com/open-telemetry/opentelemetry-erlang-contrib/tree/main/examples/basic_phoenix_ecto

**Comment by Calm-Rock** [comment]
This is the new repository that we are using for the sample app: https://github.com/SigNoz/opentelemetry-elixir-example

The instructions to instrument a phoenix + ecto application is available in our updated docs: https://signoz.io/docs/instrumentation/elixir/
