### ISSUE TITLE
Sample load from docs does not work

### ISSUE THREAD

**Issue by arrowcircle** [SigNoz/signoz.io-old#986]
Hey! Tried to run test load from official installation [docs](https://signoz.io/docs/install/kubernetes/others/#optional-install-a-sample-application-and-generate-tracing-data), but receive the error, that docker image signoz/locust:`0.8.1-py3.6` does not exist.
Any actual example on how to generate test load?

**Comment by Calm-Rock** [comment]
@arrowcircle were you able to solve this?

@prashant-shahi can you please confirm if this is working fine?

**Comment by prashant-shahi** [comment]
@arrowcircle The supported image is `signoz/locust:1.2.3` as per the default in the HOTRod installation script.

https://github.com/SigNoz/signoz/blob/develop/sample-apps/hotrod/hotrod-install.sh#L18-L19

Retrying with latest script should do the job.

**Comment by prashant-shahi** [comment]
> can you please confirm if this is working fine?

@Calm-Rock Yes, I did test it couple of days back.
